export const CHANGE_TOP_BANNERS = "CHANGE_TOP_BANNERS";
export const CHANGE_HOT_RECOMMEND = "CHANGE_HOT_RECOMMEND";
export const CHANGE_NEW_ALBUM = "CHANGE_NEW_ALBUM";
export const CHANGE_UP_LIST = "CHAGNE_UP_LIST";
export const CHANGE_NEW_LIST = "CHANGE_NEW_LIST";
export const CHANGE_ORIGIN_LIST = "CHANGE_ORIGIN_LIST";
export const CHANGE_SETTLE_SINGER = "CHANGE_SETTLE_SINGER";
