export const CHANGE_TOP_BANNERS = "CHANGE_TOP_BANNERS";
export const CHANGE_HOT_RECOMMEND = "CHANGE_HOT_RECOMMEND";
export const CHANGE_NEW_ALBUM = "CHANGE_NEW_ALBUM";
export const CHANGE_SETTLE_SINGER = "CHANGE_SETTLE_SINGER";
